project_id = "bfenuvdwsgzglhhjbrql"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.clob-relayer]
verify_jwt = false

[functions.hcs-manager]
verify_jwt = false

[functions.hcs-test]
verify_jwt = false

[functions.hedera-connectivity-test]
verify_jwt = false

[functions.request-hcs-topic]
verify_jwt = false

[functions.poll-hcs-mirror]
verify_jwt = false

[functions.get-market-comments]
verify_jwt = false

[functions.create-comment]
verify_jwt = false

[functions.toggle-reaction]
verify_jwt = false