project_id = "bfenuvdwsgzglhhjbrql"

[functions.clob-relayer]
verify_jwt = false

[functions.hcs-manager]
verify_jwt = false

[functions.hcs-test]
verify_jwt = false

[functions.process-topic-jobs]
verify_jwt = false