# source ./db/loadEnv.sh local
# source ./eventbus/loadEnv.sh local

# docker compose -f docker-compose-data.yml -f docker-compose-data.dev.yml up -d
services:
  db:
    image: ghcr.io/prismmarketlabs/db:0.1.0
    restart: always
    volumes:
      - /mnt/external/postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_UNAME}
      POSTGRES_PASSWORD: ${DB_PWORD}
      POSTGRES_DB: ${DB_NAME}

  eventbus:
    image: ghcr.io/prismmarketlabs/eventbus:0.1.0
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
