services:
  web:
    image: ghcr.io/prismmarketlabs/web:0.5.1
  api:
    #image: ghcr.io/prismmarketlabs/api:0.1.0
    deploy:
      replicas: 0
  clob:
    #image: ghcr.io/prismmarketlabs/clob:0.1.0
    deploy:
      replicas: 0
