# source ./proxy/loadEnv.sh local

# docker compose -f docker-compose-proxy.yml -f docker-compose-proxy.dev.yml up -d 
services:
  proxy:
    image: ghcr.io/prismmarketlabs/proxy:0.1.15
    # pull_policy: always
    restart: always
    ports:
      - "8090:8090"
      - "9901:9901" # admin port - be careful!
    environment:
      # IS_BASIC_AUTH_DISABLED: ${IS_BASIC_AUTH_DISABLED}
      ENVOY_HOST_CLOB: ${ENVOY_HOST_CLOB}
      ENVOY_HOST_API: ${ENVOY_HOST_API}
      ENVOY_HOST_WEB: ${ENVOY_HOST_WEB}