# docker compose -f docker-compose-monolith.yml up -d
services:
  web:
    image: ghcr.io/prismmarketlabs/web:0.1.0
  api:
    image: ghcr.io/prismmarketlabs/api:0.1.1
  clob:
    image: ghcr.io/prismmarketlabs/clob:0.1.0