# source ./proxy/loadEnv.sh local

# docker compose -f docker-compose-proxy.yml up -d 
services:
  proxy:
    image: ghcr.io/prismmarketlabs/proxy:0.1.0
    restart: always
    ports:
      - "${ENVOY_PORT}:${ENVOY_PORT}"
    network_mode: "host"
    # volumes:
    #   - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml
    environment:
      - ENVOY_PORT=${ENVOY_PORT}
      - ENVOY_ADMIN_PORT=${ENVOY_ADMIN_PORT}
      - ENVOY_WEB_HOST=${ENVOY_WEB_HOST}
      - ENVOY_WEB_PORT=${ENVOY_WEB_PORT}
      - ENVOY_API_HOST=${ENVOY_API_HOST}
      - ENVOY_API_PORT=${ENVOY_API_PORT}
      - ENVOY_CLOB_HOST=${ENVOY_CLOB_HOST}
      - ENVOY_CLOB_PORT=${ENVOY_CLOB_PORT}
