project_id = "bfenuvdwsgzglhhjbrql"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.get-market-comments]
verify_jwt = false

[functions.create-comment]
verify_jwt = false

[functions.toggle-reaction]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false
