[package]
name = "clob"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ordered-float = { version = "4.0", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
tonic = { version = "0.11", features = ["transport"] }
prost = "0.12"
prost-types = "0.12"
toml = "0.9.8"
futures-core = "0.3.31"
async-stream = "0.3.6"
async-nats = "0.33"
futures-util = "0.3"
[build-dependencies]
tonic-build = "0.11"
prost-build = "0.14.1"
