# - Ensure this repo is added to GitHub Container Registry - otherwise the push to ghcr.io will fail https://github.com/orgs/PrismMarketLabs/packages
# - Ensure you have given the Role:Write for the above step (default is Read only)
# - Ensure "Workflow permissions" has "Read and write permissions" enabled https://github.com/organizations/PrismMarketLabs/settings/actions

name: build/push (web)

on:
  repository_dispatch:
    # This specifies the event types that will trigger the workflow.
    # In this case, the workflow will run when the 'web-submodule-updated' event type occurs.
    types: [web-submodule-updated]
  push:
    paths:
      - 'web/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # N.B. the with: below is required to fetch submodules:
      with:
        ref: main
        submodules: true  # Fetch submodules
        token: ${{ secrets.READ_REPO }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}           # available by default in Actions
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        # N.B.
        context: . # can view proto files off the root
        file: ./web/Dockerfile
        push: true
        tags: |
          ghcr.io/prismmarketlabs/web:${{ github.sha}}
          ghcr.io/prismmarketlabs/web:latest
        # no-cache: true
        cache-from: type=registry,ref=ghcr.io/prismmarketlabs/web:buildcache
        cache-to: type=registry,ref=ghcr.io/prismmarketlabs/web:buildcache,mode=max