# - Ensure this repo is added to GitHub Container Registry - otherwise the push to ghcr.io will fail https://github.com/orgs/PrismMarketLabs/packages
# - Ensure you have given the Role:Write for the above step (default is Read only)
# - Ensure "Workflow permissions" has "Read and write permissions" enabled https://github.com/organizations/PrismMarketLabs/settings/actions

name: build/push (web.eng)

on:
  push:
    paths:
      - 'web.eng/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}           # available by default in Actions
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        # N.B.
        context: . # can view proto files off the root
        file: ./web.eng/Dockerfile
        push: true
        tags: |
          ghcr.io/prismmarketlabs/web.eng:${{ github.sha}}
          ghcr.io/prismmarketlabs/web.eng:latest
        cache-from: type=registry,ref=ghcr.io/prismmarketlabs/web.eng:buildcache
        cache-to: type=registry,ref=ghcr.io/prismmarketlabs/web.eng:buildcache,mode=max