name: push deployment files to S3

on:
  push:
    branches:
      - main


jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # N.B. fetch submodules
          token: ${{ secrets.READ_REPO }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # github-actions-s3-writer
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync docker-compose files to S3
        run: |
          set -x
          aws s3 cp . s3://prismlabs-deployment/ --recursive --no-follow-symlinks --exclude "*" --include "docker-compose-*"

      - name: Sync .config* and .secrets files to S3
        run: |
          for dir in api clob db eventbus proxy web; do
            aws s3 cp $dir s3://prismlabs-deployment/$dir/ \
              --recursive \
              --exclude "*" \
              --include ".config*" \
              --include ".secrets" \
              --include "loadEnv.sh"
          done